apiVersion: v1
kind: Template
labels:
  template: docs-ci-setup
metadata:
  name: docs-ci-setup
parameters:
- name: NAME
  description: The name of the build to create
  displayName: Build Name
  value: docs-ci-setup
  required: true
- name: SOURCE_URL
  description: The URL of the source repository that has the Jenkinsfile to run the setup
  displayName: Jenkinsfile Source URL
  value: https://github.com/csrwng/docs-ci.git
  required: true
- name: SOURCE_REF
  description: The Ref of the source repository that has the Jenkinsfile to run the setup
  displayName: Jenkinsfile Source Ref
  value: master
  required: true
objects:
- apiVersion: v1
  kind: RoleBinding
  metadata:
    name: jenkins_admin
  roleRef:
    name: admin
  subjects:
  - kind: ServiceAccount
    name: jenkins
  - kind: ServiceAccount
    name: docs-ci-jenkins
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      name: "${NAME}"
    name: "${NAME}"
  spec:
    source:
      git: 
        uri: https://github.com/csrwng/docs-ci.git
        ref: master
    strategy:
      jenkinsPipelineStrategy: {}
      type: JenkinsPipeline
    triggers:
    - type: ConfigChange
